config/routes.rb
APP_NAME::Application.routes.draw do
  get    '/session/new' => 'sessions#new',     as: :sign_in
  delete '/session'     => 'sessions#destroy', as: :sign_out
  match  '/auth/:provider/callback' => 'sessions#create',  via: :all
  match  '/auth/failure'            => 'sessions#failure', via: :all

  resources :invitation_requests, except: %i(show edit update) do
    post '/send' => 'invitation_requests#send_invitation', as: :send
  end
  resources :memberships, only: %i(create destroy)
  resource  :snapshot, only: %i(create)
  resources :teams

  root to: 'teams#index'
end

app/models/invitation_request.rb
class InvitationRequest < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
end

app/controllers/invitation_requests_controller.rb
class InvitationRequestsController < AuthenticatedController
  respond_to :html

  skip_before_filter :authenticate, only: %i(new create)

  def index
    @invitation_requests = InvitationRequest.all
  end

  def new
    @invitation_request = InvitationRequest.new
  end

  def create
    @invitation_request = InvitationRequest.new(invitation_request_params)

    if @invitation_request.save
      redirect_to root_path, notice: t('invitation_request.create.success')
    else
      render :new
    end
  end

  def destroy
    invitation_request = InvitationRequest.find(params[:id])
    invitation_request.destroy!
    respond_with invitation_request
  end

  def send_invitation
    invitation_request = InvitationRequest.find_by_id(params[:invitation_request_id])

    if invitation_request
      invitation = Invitation.create!
      InvitationMailer.send_invitation(invitation_request, invitation).deliver
      invitation_request.destroy!
      redirect_to root_path, notice: t('invitation_request.sent')
    else
      redirect_to root_path, alert: t('invitation_request.not_found')
    end
  end

  private

  def invitation_request_params
    params.require(:invitation_request).permit(:email)
  end
end

app/helpers/invitation_requests_helper.rb
module InvitationRequestsHelper
  def send_invitation_link(request)
    link_to(
      'Send Invitation',
      invitation_request_send_path(request),
      method: :post,
      rel:    'send-invitation',
      class:  %i(btn btn-inverse),
    )
  end

  def delete_invitation_request_link(request)
    link_to(
      'Delete Request',
      invitation_request_path(request),
      method: :delete,
      data:   {confirm: 'Sure?'},
      class:  %i(btn btn-danger),
    )
  end
end

app/views/invitation_requests/_count_alert.html.haml
- request_count = InvitationRequest.count
- if request_count > 0
  .alert.alert-info
    There are <strong>#{request_count}</strong> people wanting an
    invitation to snapme!
    Can you #{link_to 'help them out', invitation_requests_path}?

app/views/invitation_requests/index.html.haml
.pull-right
  = link_to 'View Teams', teams_path, class: %i(btn btn-primary)
%h1 Invitation Requests
%p
  For now Snapme is invitation only. Our privacy is important, so we don't want
  to simply let anyone in with a provider account. Please choose wisely in
  sending invitations to requesting users!

%table.table
  %thead
    %tr
      %th Email
  %tbody
    - @invitation_requests.each do |request|
      %tr.invitation-request
        %td= request.email
        %td
          .pull-right
            = send_invitation_link(request)
            = delete_invitation_request_link(request)

app/views/invitation_requests/new.html.haml
.row
  .span6.offset3
    = form_for @invitation_request do |f|
      - if @invitation_request.errors.any?
        .alert.alert-error
          %ul(style='margin-bottom:0')
            - @invitation_request.errors.full_messages.each do |error|
              %li= error
      = f.email_field :email, placeholder: 'Email address to send your invitation', class: :span12
      .actions.text-center= f.submit 'Send your request!', class: %i(btn btn-primary), rel: 'send-request'