config/routes.rb
APP_NAME::Application.routes.draw do
  get    '/session/new' => 'sessions#new',     as: :sign_in
  delete '/session'     => 'sessions#destroy', as: :sign_out
  match  '/auth/:provider/callback' => 'sessions#create',  via: :all
  match  '/auth/failure'            => 'sessions#failure', via: :all

  resources :invitation_requests, except: %i(show edit update) do
    post '/send' => 'invitation_requests#send_invitation', as: :send
  end
  resources :memberships, only: %i(create destroy)
  resource  :snapshot, only: %i(create)
  resources :teams

  root to: 'teams#index'
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Snapme
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      .row-fluid
        .span12
          - if alert
            .alert.alert-error= alert
          - if notice
            .alert.alert-info.disappear= notice

          - if current_user
            %div
              .pull-right= link_to 'Sign out', sign_out_path, method: :delete, rel: 'sign-out', class: %i(btn btn-danger)
              %h2
                %small Hey there,
                = current_user.username
              %p
                Your auth token is <code>#{current_user.auth_token}</code>.
                Start uploading snapshots with the CLI <code>gem install snapme</code>.
          - else
            .row.demo-tiles(style='margin-bottom:20px')
              .span6.offset3
                .tile
                  %h1 Welcome!
                  %p
                    Snapme let's you get a glipse at your team from anywhere!
                    We ask for the least authorization possible from your
                    chosen auth provider.

                  = link_to 'Want in?', new_invitation_request_path, rel: 'request-invitation', class: %i(btn btn-warning btn-large)

          %hr/
          = yield

          = javascript_include_tag 'http://js.pusher.com/2.1/pusher.min.js'
          = javascript_include_tag 'application', 'data-turbolinks-track' => true